# Autogenerated wrapper script for CmdStanBinaries_jll for x86_64-linux-gnu
export diagnose, print_deprecated, stanc, stansummary

JLLWrappers.@generate_wrapper_header("CmdStanBinaries")
JLLWrappers.@declare_executable_product(diagnose)
JLLWrappers.@declare_executable_product(print_deprecated)
JLLWrappers.@declare_executable_product(stanc)
JLLWrappers.@declare_executable_product(stansummary)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        diagnose,
        "bin/diagnose",
    )

    JLLWrappers.@init_executable_product(
        print_deprecated,
        "bin/print",
    )

    JLLWrappers.@init_executable_product(
        stanc,
        "bin/stanc",
    )

    JLLWrappers.@init_executable_product(
        stansummary,
        "bin/stansummary",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
